earthquake_queries = [
    "What is an earthquake and how does it occur?",
    "What causes earthquakes to happen?",
    "How are earthquakes measured?",
    "What is the Richter scale used for?",
    "What are tectonic plates and how do they relate to earthquakes?",
    "What is the difference between magnitude and intensity?",
    "How do aftershocks differ from the main earthquake?",
    "What are the signs that an earthquake might occur?",
    "Can animals sense earthquakes before they happen?",
    "How do I know if my area is earthquake-prone?",
    "What should I do during an earthquake?",
    "What are the safest places to take cover during an earthquake?",
    "What should I avoid doing during an earthquake?",
    "How do I prepare my home for an earthquake?",
    "What items should be in an earthquake emergency kit?",
    "How do I create an earthquake evacuation plan for my family?",
    "What should I do if I’m in a classroom during an earthquake?",
    "How do schools prepare for earthquake emergencies?",
    "What should I do if I’m in a college hostel during an earthquake?",
    "How do I protect my pets during an earthquake?",
    "What are the do’s and don’ts during an earthquake?",
    "How do I stay safe if I live in a hilly area?",
    "What should I do if I’m stuck outside during an earthquake?",
    "How do I protect important documents during an earthquake?",
    "What foods should I store for earthquake emergencies?",
    "How do I keep my phone charged during a power outage?",
    "What should I do if my building starts shaking?",
    "How do I know when it’s safe to return home?",
    "What precautions should I take after an earthquake?",
    "How do I disinfect water after an earthquake?",
    "What are common injuries during earthquakes and how to treat them?",
    "How do I support friends emotionally after an earthquake?",
    "What should I do if my earthquake shelter is full?",
    "How do I help elderly neighbors evacuate safely?",
    "What are the risks of landslides in hilly areas during earthquakes?",
    "How do I secure windows and doors before an earthquake?",
    "What should I do if I’m in a moving vehicle during an earthquake?",
    "How do I protect electronics from earthquake damage?",
    "What are the emergency numbers I should save?",
    "How do I prepare my college dorm for earthquake safety?",
    "What should I teach kids about earthquake safety?",
    "How do I help someone with a disability during an earthquake?",
    "What should I do if I lose communication during an earthquake?",
    "How do I find earthquake relief centers near me?",
    "What apps send real-time earthquake alerts?",
    "How do I prepare my vehicle for evacuation?",
    "What should I do if my classroom ceiling starts cracking?",
    "How do I stay informed if the internet goes down?",
    "What are the signs of post-earthquake trauma?",
    "How do I clean up safely after an earthquake?",
    "What should I do if my house is damaged?",
    "How do I report earthquake damage?",
    "What should I do if my pet goes missing during an earthquake?",
    "How do I protect livestock during an earthquake?",
    "What are the safest places in a school building during an earthquake?",
    "How do I prepare mentally for earthquake emergencies?",
    "What should I do if I’m alone during an earthquake?",
    "How do I protect my rooftop water tank?",
    "What should I do if my college campus is under earthquake alert?",
    "How do I help classmates during an earthquake evacuation?",
    "What are the risks of staying in high-rise buildings?",
    "How do I protect glass windows in classrooms?",
    "What should I do if my school bus is caught in an earthquake?",
    "How do I prepare my hostel room for earthquake safety?",
    "What should I do if my building’s power fails?",
    "How do I keep children calm during an earthquake?",
    "What should I do if I hear conflicting earthquake information?",
    "How do I protect myself from falling debris?",
    "What should I do if I feel unsafe in my current shelter?",
    "How do I check if my house is structurally safe?",
    "What should I do if my earthquake shelter lacks supplies?",
    "How do I help clean up debris safely?",
    "What should I do if my college loses power?",
    "How do I protect school supplies from water damage?",
    "What should I do if my pet is scared during an earthquake?",
    "How do I prepare my hilltop home for earthquake safety?",
    "What should I do if I’m traveling during an earthquake?",
    "How do I stay safe in a mountain resort during an earthquake?",
    "What should I do if my school is used as a shelter?",
    "How do I help teachers manage students during an earthquake?",
    "What should I do if my family is in another city?",
    "How do I prepare my apartment for earthquake safety?",
    "What should I do if my college exams are scheduled during an earthquake?",
    "How do I protect classroom electronics?",
    "What should I do if I’m in a temporary shelter?",
    "How do I help someone who’s injured during an earthquake?",
    "What should I do if my building’s elevator stops working?",
    "How do I prepare my hill station business for earthquake impact?",
    "What should I do if my pet refuses to evacuate?",
    "How do I protect books and study materials?",
    "What should I do if I’m in a crowded shelter?",
    "How do I prepare my school bag for earthquake emergencies?",
    "What should I do if my college hostel is damaged?",
    "How do I help classmates with anxiety during an earthquake?",
    "What should I do if my family is unreachable?",
    "How do I protect my bicycle or scooter?",
    "What should I do if my school has no earthquake protocol?",
    "How do I prepare my hillside café for earthquake season?",
    "What should I do if my college library is damaged?",
    "How do I help clean up my classroom after an earthquake?",
    "What should I do if my pet needs medical help?",
    "How do I stay safe in an earthquake-prone hilly town?",
    "What should I do if my school is closed due to earthquake?",
    "How do I prepare my family for earthquake drills?",
    "What should I do if my college hostel lacks emergency supplies?",
    "How do I protect my home from earthquake damage?",
    "What should I do if I’m in a lift during an earthquake?",
    "How do I prepare my building’s foundation for earthquakes?",
    "What should I do if my school building is old and unsafe?",
    "How do I protect myself if I’m in a crowded auditorium?",
    "What should I do if my college has no evacuation plan?",
    "How do I help someone who’s unconscious after an earthquake?",
    "What should I do if my classroom furniture is unstable?",
    "How do I prepare my hilltop school for earthquake safety?",
    "What should I do if my pet is trapped in rubble?",
    "How do I protect my family’s health after an earthquake?",
    "What should I do if I’m in a hospital during an earthquake?",
    "How do I prepare my college lab for earthquake safety?",
    "What should I do if my school’s emergency exit is blocked?",
    "How do I help someone having a panic attack during an earthquake?",
    "What should I do if my building’s staircase is damaged?",
    "How do I prepare my hill village for earthquake response?",
    "What should I do if my college hostel has structural cracks?",
    "How do I protect myself if I’m in a basement during an earthquake?",
    "What should I do if my school roof collapses?",
    "How do I prepare my family’s health kit for earthquake emergencies?",
    "What should I do if my college has no first aid supplies?",
    "How do I help someone with asthma during an earthquake?",
    "What should I do if my classroom has broken glass?",
    "How do I prepare my hilltop resort for earthquake safety?",
    "What should I do if my school’s water supply is disrupted?",
    "How do I protect myself if I’m in a crowded market?",
    "What should I do if my college hostel is overcrowded?",
    "How do I prepare my family’s emergency contact list?",
    "What should I do if my school’s communication system fails?",
    "How do I help someone who’s lost their belongings?",
    "What should I do if my college has no backup power?",
    "How do I prepare my hill community for earthquake drills?"
]

flood_queries = [
    "What is a flood and how does it occur?",
    "What causes rivers to overflow during floods?",
    "How does urbanization increase flood risk?",
    "What are flash floods and how are they different?",
    "How do I know if my area is flood-prone?",
    "What are the early warning signs of a flood?",
    "How do I receive flood alerts in my region?",
    "What should I do when a flood warning is issued?",
    "How can I prepare my house for flood season?",
    "What items should be in a flood emergency kit?",
    "How do I create a flood evacuation plan for my family?",
    "Where can I find the nearest flood shelter?",
    "What are the safest places to stay during a flood?",
    "How do I protect my pets during a flood?",
    "What should I do if I’m at school when flooding starts?",
    "How do schools prepare for flood emergencies?",
    "What are the do’s and don’ts during a flood?",
    "How do I stay safe if I live near a river?",
    "What should I avoid doing during a flood?",
    "How do I help someone who is panicking during a flood?",
    "What should I do if I get separated from my family?",
    "How do I protect important documents during a flood?",
    "What foods should I store for flood emergencies?",
    "How do I keep my phone charged during a power outage?",
    "What should I do if my house starts flooding?",
    "How do I know when it’s safe to return home?",
    "What precautions should I take after a flood?",
    "How do I disinfect water after a flood?",
    "What diseases are common after floods?",
    "How do I treat minor injuries during a flood?",
    "How do I support friends emotionally after a flood?",
    "What should I do if my flood shelter is full?",
    "How do I help elderly neighbors evacuate safely?",
    "What are the risks of staying near a swollen river?",
    "How do I secure windows and doors before a flood?",
    "What should I do if I’m stuck outside during a flood?",
    "How do I protect electronics from flood damage?",
    "What emergency numbers should I save before flood season?",
    "How do I prepare my college dorm for flood safety?",
    "What should I teach kids about flood safety?",
    "How do I help someone with a disability during a flood?",
    "What should I do if I lose communication during a flood?",
    "How do I find flood relief centers near me?",
    "What apps send real-time flood alerts?",
    "How do I prepare my vehicle for flood evacuation?",
    "What should I do if my classroom floods?",
    "How do I stay informed if the internet goes down?",
    "What are the signs of post-flood trauma?",
    "How do I clean up safely after a flood?",
    "What should I do if my house is damaged by floodwater?",
    "How do I report flood damage?",
    "What should I do if my pet goes missing during a flood?",
    "How do I protect livestock during a flood?",
    "What are the safest places in a school building during a flood?",
    "How do I prepare mentally for flood emergencies?",
    "What should I do if I’m alone during a flood?",
    "How do I protect my rooftop water tank from contamination?",
    "What should I do if my college campus is under flood alert?",
    "How do I help classmates during a flood evacuation?",
    "What are the risks of staying in low-lying buildings?",
    "How do I protect glass windows in classrooms?",
    "What should I do if my school bus is caught in floodwaters?",
    "How do I prepare my hostel room for flood safety?",
    "What should I do if my building’s power fails during a flood?",
    "How do I keep children calm during a flood?",
    "What should I do if I hear conflicting flood information?",
    "How do I protect myself from contaminated water?",
    "What should I do if I feel unsafe in my current shelter?",
    "How do I check if my house is structurally safe after a flood?",
    "What should I do if my flood shelter lacks basic supplies?",
    "How do I help clean up debris safely after a flood?",
    "What should I do if my college loses power during a flood?",
    "How do I protect school supplies from water damage?",
    "What should I do if my pet is scared during a flood?",
    "How do I prepare my riverside home for flood season?",
    "What should I do if I’m traveling during a flood alert?",
    "How do I stay safe in a boat during flood conditions?",
    "What should I do if my school is used as a flood shelter?",
    "How do I help teachers manage students during a flood?",
    "What should I do if my family is in another city during a flood?",
    "How do I prepare my apartment for flood safety?",
    "What should I do if my college exams are scheduled during a flood?",
    "How do I protect classroom electronics from flood damage?",
    "What should I do if I’m in a temporary shelter?",
    "How do I help someone who’s injured during a flood?",
    "What should I do if my building’s elevator stops working?",
    "How do I prepare my riverside business for flood impact?",
    "What should I do if my pet refuses to evacuate?",
    "How do I protect books and study materials from flood damage?",
    "What should I do if I’m in a crowded shelter?",
    "How do I prepare my school bag for flood emergencies?",
    "What should I do if my college hostel is flooded?",
    "How do I help classmates with anxiety during a flood?",
    "What should I do if my family is unreachable during a flood?",
    "How do I protect my bicycle or scooter from flood damage?",
    "What should I do if my school has no flood protocol?",
    "How do I prepare my riverside café for flood season?",
    "What should I do if my college library is damaged by flood?",
    "How do I help clean up my classroom after a flood?",
    "What should I do if my pet needs medical help during a flood?",
    "How do I stay safe in a flood-prone riverside town?",
    "What should I do if my school is closed due to flooding?",
    "How do I prepare my family for flood drills?",
    "What should I do if my college hostel lacks emergency supplies?",
    "How do I protect my home from rising water levels?",
    "What should I do if I’m in a lift during a flood?",
    "How do I prepare my building’s foundation for flood resistance?",
    "What should I do if my school building is old and flood-prone?",
    "How do I protect myself if I’m in a crowded auditorium during a flood?",
    "What should I do if my college has no evacuation plan?",
    "How do I help someone who’s unconscious after a flood?",
    "What should I do if my classroom furniture is floating?",
    "How do I prepare my riverside school for flood safety?",
    "What should I do if my pet is trapped in rising water?",
    "How do I protect my family’s health after a flood?",
    "What should I do if I’m in a hospital during a flood?",
    "How do I prepare my college lab for flood safety?",
    "What should I do if my school’s emergency exit is blocked?",
    "How do I help someone having a panic attack during a flood?",
    "What should I do if my building’s staircase is underwater?",
    "How do I prepare my river village for flood response?",
    "What should I do if my college hostel has structural cracks?",
    "How do I protect myself if I’m in a basement during a flood?",
    "What should I do if my school roof collapses during a flood?",
    "How do I prepare my family’s health kit for flood emergencies?",
    "What should I do if my college has no first aid supplies?",
    "How do I help someone with asthma during a flood?",
    "What should I do if my classroom has standing water?",
    "How do I prepare my riverside resort for flood safety?",
    "What should I do if my school’s water supply is disrupted?",
    "How do I protect myself if I’m in a crowded market during a flood?",
    "What should I do if my college hostel is overcrowded?",
    "How do I prepare my family’s emergency contact list for floods?",
    "What should I do if my school’s communication system fails?",
    "How do I help someone who’s lost their belongings in a flood?",
    "What should I do if my college has no backup power?",
    "How do I prepare my river community for flood drills?"
]


fire_queries = [
    "What is fire and how does it start?",
    "What are the common causes of fire in homes?",
    "How do electrical fires occur?",
    "What is a forest fire and how does it spread?",
    "What should I do when a fire alarm goes off?",
    "How do I evacuate safely during a fire?",
    "What items should be in a fire emergency kit?",
    "How do I create a fire escape plan for my family?",
    "What are the do’s and don’ts during a fire emergency?",
    "How do I use a fire extinguisher properly?",
    "What are the different types of fire extinguishers?",
    "How do I know which fire extinguisher to use?",
    "What should I do if someone gets burned?",
    "How do I treat minor burns at home?",
    "What are the signs of smoke inhalation?",
    "How do I protect pets during a fire?",
    "What should I do if my pet is trapped in a burning building?",
    "How do schools prepare for fire emergencies?",
    "What should I do if I’m in a classroom during a fire?",
    "How do I help classmates evacuate during a fire?",
    "What should I do if I’m in a college hostel during a fire?",
    "How do I protect important documents from fire damage?",
    "What are the safest places to shelter during a fire?",
    "How do I stay calm during a fire evacuation?",
    "What should I do if I’m trapped in a burning building?",
    "How do I signal for help if I’m trapped during a fire?",
    "What should I do if my building’s fire exit is blocked?",
    "How do I help someone with a disability evacuate during a fire?",
    "What are the risks of using elevators during a fire?",
    "How do I prepare my house for fire safety?",
    "What are the fire safety rules for cooking at home?",
    "How do I prevent electrical fires in my building?",
    "What should I do if my school bus catches fire?",
    "How do I protect livestock during a farm fire?",
    "What should I do if a jungle fire is approaching my village?",
    "How do I help animals escape during a forest fire?",
    "What are the signs of a fire starting in a building?",
    "How do I report a fire emergency?",
    "What should I do if I see smoke in my apartment?",
    "How do I protect myself from toxic fumes during a fire?",
    "What are the symptoms of fire-related trauma?",
    "How do I help someone who’s unconscious during a fire?",
    "What should I do if my clothes catch fire?",
    "How do I stop, drop, and roll correctly?",
    "What should I do if my college has no fire evacuation plan?",
    "How do I prepare my classroom for fire safety?",
    "What should I do if my school’s fire alarm doesn’t work?",
    "How do I help someone having a panic attack during a fire?",
    "What should I do if my building’s staircase is filled with smoke?",
    "How do I prepare my village for fire drills?",
    "What should I do if my college hostel has no fire extinguishers?",
    "How do I protect myself if I’m in a basement during a fire?",
    "What should I do if my school roof catches fire?",
    "How do I prepare my family’s health kit for fire emergencies?",
    "What should I do if my college has no first aid supplies?",
    "How do I help someone with asthma during a fire?",
    "What should I do if my classroom has flammable materials?",
    "How do I prepare my jungle resort for fire safety?",
    "What should I do if my school’s water supply is disrupted during a fire?",
    "How do I protect myself if I’m in a crowded market during a fire?",
    "What should I do if my college hostel is overcrowded during evacuation?",
    "How do I prepare my family’s emergency contact list for fire emergencies?",
    "What should I do if my school’s communication system fails during a fire?",
    "How do I help someone who’s lost their belongings in a fire?",
    "What should I do if my college has no backup power during a fire?",
    "How do I prepare my farm for fire prevention?",
    "What should I do if my pet is injured in a fire?",
    "How do I protect books and study materials from fire damage?",
    "What should I do if I’m in a crowded shelter during a fire?",
    "How do I prepare my school bag for fire emergencies?",
    "What should I do if my college hostel is damaged by fire?",
    "How do I help classmates with anxiety during a fire?",
    "What should I do if my family is unreachable during a fire?",
    "How do I protect my bicycle or scooter from fire damage?",
    "What should I do if my school has no fire protocol?",
    "How do I prepare my jungle café for fire season?",
    "What should I do if my college library is damaged by fire?",
    "How do I help clean up my classroom after a fire?",
    "What should I do if my pet needs medical help after a fire?",
    "How do I stay safe in a fire-prone jungle town?",
    "What should I do if my school is closed due to fire damage?",
    "How do I prepare my family for fire drills?",
    "What should I do if my college hostel lacks emergency supplies?",
    "How do I protect my home from fire hazards?",
    "What should I do if I’m in a lift during a fire?",
    "How do I prepare my building’s foundation for fire safety?",
    "What should I do if my school building is old and unsafe?",
    "How do I protect myself if I’m in a crowded auditorium during a fire?",
    "What should I do if my college has no fire extinguishers?",
    "How do I help someone who’s burned and in shock?",
    "What should I do if my classroom furniture is flammable?",
    "How do I prepare my jungle school for fire safety?",
    "What should I do if my pet is trapped in rubble after a fire?",
    "How do I protect my family’s health after a fire?",
    "What should I do if I’m in a hospital during a fire?",
    "How do I prepare my college lab for fire safety?",
    "What should I do if my school’s emergency exit is blocked?",
    "How do I help someone having breathing issues during a fire?",
    "What should I do if my building’s staircase is damaged by fire?",
    "How do I prepare my jungle village for fire response?",
    "What should I do if my college hostel has structural cracks from fire?",
    "How do I protect myself if I’m in a basement with smoke?",
    "What should I do if my school roof collapses during a fire?",
    "How do I prepare my family’s fire safety checklist?",
    "What should I do if my college has no fire alarms?",
    "How do I help someone with burns until help arrives?",
    "What should I do if my classroom has exposed wires?",
    "How do I prepare my jungle resort for fire evacuation?",
    "What should I do if my school’s fire exit is locked?",
    "How do I protect myself if I’m in a crowded train during a fire?",
    "What should I do if my college hostel is overcrowded during fire evacuation?",
    "How do I prepare my family’s emergency plan for fire?",
    "What should I do if my school’s fire drill is outdated?",
    "How do I help someone who’s lost their pet in a fire?",
    "What should I do if my college has no fire escape route?",
    "How do I prepare my farm animals for fire evacuation?",
    "What should I do if my pet is hiding during a fire?",
    "How do I protect myself from smoke in a jungle fire?",
    "What should I do if my school’s fire extinguisher is missing?",
    "How do I prepare my village for fire safety awareness?",
    "What should I do if my college hostel has no fire exit?",
    "How do I help someone who’s disoriented during a fire?",
    "What should I do if my classroom has blocked windows?",
    "How do I prepare my jungle community for fire drills?",
    "What should I do if my pet is missing after a fire?",
    "How do I protect my family’s medical supplies during a fire?",
    "What should I do if I’m in a boat during a fire emergency?",
    "How do I prepare my ambulance team for fire response?",
    "What should I do if my college has no fire safety officer?",
    "How do I help someone who’s trapped in a burning vehicle?",
    "What should I do if my school’s fire exit is obstructed?",
    "How do I prepare my jungle school for fire evacuation?",
    "What should I do if my pet is injured and hiding?",
    "How do I protect myself from heatstroke during a fire?",
    "What should I do if my college hostel has no fire signage?",
    "How do I prepare my jungle village for fire rescue coordination?"
]
cyclone_queries = [
    "What is a cyclone and how does it form?",
    "How are cyclones different from hurricanes or typhoons?",
    "What causes cyclones to intensify rapidly?",
    "How does climate change affect cyclone frequency?",
    "What are the early warning signs of a cyclone?",
    "How do I know if my area is under cyclone watch or warning?",
    "What should I do when a c    yclone alert is issued?",
    "How can I prepare my home before cyclone season?",
    "What items should be in a cyclone emergency kit?",
    "How do I create a cyclone evacuation plan for my family?",
    "Where can I find official cyclone updates and alerts?",
    "What are the safest places to shelter during a cyclone?",
    "How do I protect my pets during a cyclone?",
    "What should I do if I’m at school when a cyclone hits?",
    "How do schools prepare for cyclone emergencies?",
    "What are the do’s and don’ts during a cyclone?",
    "How do I stay safe if I live near the coast?",
    "What should I avoid doing during a cyclone?",
    "How do I help someone who is panicking during a cyclone?",
    "What should I do if I get separated from my family?",
    "How do I protect important documents during a cyclone?",
    "What foods should I store for cyclone emergencies?",
    "How do I keep my phone charged during a power outage?",
    "What should I do if my building starts flooding?",
    "How do I know when it’s safe to return home?",
    "What precautions should I take after a cyclone passes?",
    "How do I disinfect water after a cyclone?",
    "What are common injuries during cyclones and how to treat them?",
    "How do I support friends emotionally after a cyclone?",
    "What should I do if my cyclone shelter is full?",
    "How do I help elderly neighbors evacuate safely?",
    "What are the risks of staying near the beach during a cyclone?",
    "How do I secure windows and doors before a cyclone?",
    "What should I do if I’m stuck outside during a cyclone?",
    "How do I protect electronics from cyclone damage?",
    "What are the emergency numbers I should save?",
    "How do I prepare my college dorm for cyclone season?",
    "What should I teach kids about cyclone safety?",
    "How do I help someone with a disability during a cyclone?",
    "What should I do if I lose communication during a cyclone?",
    "How do I find cyclone relief centers near me?",
    "What apps send real-time cyclone alerts?",
    "How do I prepare my vehicle for evacuation?",
    "What should I do if my classroom floods?",
    "How do I stay informed if the internet goes down?",
    "What are the signs of post-cyclone trauma?",
    "How do I clean up safely after a cyclone?",
    "What should I do if my house is damaged?",
    "How do I report cyclone damage?",
    "What should I do if my pet goes missing during a cyclone?",
    "How do I protect livestock during a cyclone?",
    "What are the safest places in a school building during a cyclone?",
    "How do I prepare mentally for cyclone emergencies?",
    "What should I do if I’m alone during a cyclone?",
    "How do I protect my rooftop water tank?",
    "What should I do if my college campus is under cyclone alert?",
    "How do I help classmates during a cyclone evacuation?",
    "What are the risks of staying in high-rise buildings?",
    "How do I protect glass windows in classrooms?",
    "What should I do if my school bus is caught in a cyclone?",
    "How do I prepare my hostel room for cyclone safety?",
    "What should I do if my building’s power fails?",
    "How do I keep children calm during a cyclone?",
    "What should I do if I hear conflicting cyclone information?",
    "How do I protect myself from flying debris?",
    "What should I do if I feel unsafe in my current shelter?",
    "How do I check if my house is structurally safe?",
    "What should I do if my cyclone shelter lacks supplies?",
    "How do I help clean up debris safely?",
    "What should I do if my college loses power?",
    "How do I protect school supplies from water damage?",
    "What should I do if my pet is scared during a cyclone?",
    "How do I prepare my coastal home for cyclone season?",
    "What should I do if I’m traveling during a cyclone alert?",
    "How do I stay safe in a beach resort during a cyclone?",
    "What should I do if my school is used as a shelter?",
    "How do I help teachers manage students during a cyclone?",
    "What should I do if my family is in another city?",
    "How do I prepare my apartment for cyclone safety?",
    "What should I do if my college exams are scheduled during a cyclone?",
    "How do I protect classroom electronics?",
    "What should I do if I’m in a temporary shelter?",
    "How do I help someone who’s injured during a cyclone?",
    "What should I do if my building’s elevator stops working?",
    "How do I prepare my coastal business for cyclone impact?",
    "What should I do if my pet refuses to evacuate?",
    "How do I protect books and study materials?",
    "What should I do if I’m in a crowded shelter?",
    "How do I prepare my school bag for cyclone emergencies?",
    "What should I do if my college hostel is flooded?",
    "How do I help classmates with anxiety during a cyclone?",
    "What should I do if my family is unreachable?",
    "How do I protect my bicycle or scooter?",
    "What should I do if my school has no cyclone protocol?",
    "How do I prepare my beachside café for cyclone season?",
    "What should I do if my college library is damaged?",
    "How do I help clean up my classroom after a cyclone?",
    "What should I do if my pet needs medical help?",
    "How do I stay safe in a cyclone-prone coastal town?",
    "What should I do if my school is closed due to cyclone?",
    "How do I prepare my family for cyclone drills?",
    "What should I do if my college hostel lacks emergency supplies?"
]
landslide_queries = [
    "What is a landslide and how does it occur?",
    "What causes landslides in hilly areas?",
    "How can heavy rainfall trigger landslides?",
    "What are the warning signs of a landslide?",
    "How do I know if my area is landslide-prone?",
    "What types of landslides are most dangerous?",
    "How do landslides differ from mudslides?",
    "Can earthquakes trigger landslides?",
    "What should I do during a landslide?",
    "What are the safest places to take cover during a landslide?",
    "What should I avoid doing during a landslide?",
    "How do I prepare my home for landslide safety?",
    "What items should be in a landslide emergency kit?",
    "How do I create a landslide evacuation plan for my family?",
    "What should I do if I’m in a classroom during a landslide?",
    "How do schools prepare for landslide emergencies?",
    "What should I do if I’m in a college hostel during a landslide?",
    "How do I protect my pets during a landslide?",
    "What are the do’s and don’ts during a landslide?",
    "How do I stay safe if I live on a slope?",
    "What should I do if I’m stuck outside during a landslide?",
    "How do I protect important documents during a landslide?",
    "What foods should I store for landslide emergencies?",
    "How do I keep my phone charged during a power outage?",
    "What should I do if my building starts sliding?",
    "How do I know when it’s safe to return home?",
    "What precautions should I take after a landslide?",
    "How do I disinfect water after a landslide?",
    "What are common injuries during landslides and how to treat them?",
    "How do I support friends emotionally after a landslide?",
    "What should I do if my landslide shelter is full?",
    "How do I help elderly neighbors evacuate safely?",
    "What are the risks of landslides in monsoon season?",
    "How do I secure windows and doors before a landslide?",
    "What should I do if I’m in a moving vehicle during a landslide?",
    "How do I protect electronics from landslide damage?",
    "What are the emergency numbers I should save?",
    "How do I prepare my college dorm for landslide safety?",
    "What should I teach kids about landslide safety?",
    "How do I help someone with a disability during a landslide?",
    "What should I do if I lose communication during a landslide?",
    "How do I find landslide relief centers near me?",
    "What apps send real-time landslide alerts?",
    "How do I prepare my vehicle for evacuation?",
    "What should I do if my classroom ceiling starts cracking?",
    "How do I stay informed if the internet goes down?",
    "What are the signs of post-landslide trauma?",
    "How do I clean up safely after a landslide?",
    "What should I do if my house is damaged?",
    "How do I report landslide damage?",
    "What should I do if my pet goes missing during a landslide?",
    "How do I protect livestock during a landslide?",
    "What are the safest places in a school building during a landslide?",
    "How do I prepare mentally for landslide emergencies?",
    "What should I do if I’m alone during a landslide?",
    "How do I protect my rooftop water tank?",
    "What should I do if my college campus is under landslide alert?",
    "How do I help classmates during a landslide evacuation?",
    "What are the risks of staying in hillside buildings?",
    "How do I protect glass windows in classrooms?",
    "What should I do if my school bus is caught in a landslide?",
    "How do I prepare my hostel room for landslide safety?",
    "What should I do if my building’s power fails?",
    "How do I keep children calm during a landslide?",
    "What should I do if I hear conflicting landslide information?",
    "How do I protect myself from falling debris?",
    "What should I do if I feel unsafe in my current shelter?",
    "How do I check if my house is structurally safe?",
    "What should I do if my landslide shelter lacks supplies?",
    "How do I help clean up debris safely?",
    "What should I do if my college loses power?",
    "How do I protect school supplies from water damage?",
    "What should I do if my pet is scared during a landslide?",
    "How do I prepare my hilltop home for landslide safety?",
    "What should I do if I’m traveling during a landslide?",
    "How do I stay safe in a mountain resort during a landslide?",
    "What should I do if my school is used as a shelter?",
    "How do I help teachers manage students during a landslide?",
    "What should I do if my family is in another city?",
    "How do I prepare my apartment for landslide safety?",
    "What should I do if my college exams are scheduled during a landslide?",
    "How do I protect classroom electronics?",
    "What should I do if I’m in a temporary shelter?",
    "How do I help someone who’s injured during a landslide?",
    "What should I do if my building’s elevator stops working?",
    "How do I prepare my hill station business for landslide impact?",
    "What should I do if my pet refuses to evacuate?",
    "How do I protect books and study materials?",
    "What should I do if I’m in a crowded shelter?",
    "How do I prepare my school bag for landslide emergencies?",
    "What should I do if my college hostel is damaged?",
    "How do I help classmates with anxiety during a landslide?",
    "What should I do if my family is unreachable?",
    "How do I protect my bicycle or scooter?",
    "What should I do if my school has no landslide protocol?",
    "How do I prepare my hillside café for landslide season?",
    "What should I do if my college library is damaged?",
    "How do I help clean up my classroom after a landslide?",
    "What should I do if my pet needs medical help?",
    "How do I stay safe in a landslide-prone hilly town?",
    "What should I do if my school is closed due to landslide?",
    "How do I prepare my family for landslide drills?",
    "What should I do if my college hostel lacks emergency supplies?",
    "How do I protect my home from landslide damage?",
    "What should I do if I’m in a lift during a landslide?",
    "How do I prepare my building’s foundation for landslides?",
    "What should I do if my school building is old and unsafe?",
    "How do I protect myself if I’m in a crowded auditorium?",
    "What should I do if my college has no evacuation plan?",
    "How do I help someone who’s unconscious after a landslide?",
    "What should I do if my classroom furniture is unstable?",
    "How do I prepare my hilltop school for landslide safety?",
    "What should I do if my pet is trapped in rubble?",
    "How do I protect my family’s health after a landslide?",
    "What should I do if I’m in a hospital during a landslide?",
    "How do I prepare my college lab for landslide safety?",
    "What should I do if my school’s emergency exit is blocked?",
    "How do I help someone having a panic attack during a landslide?",
    "What should I do if my building’s staircase is damaged?",
    "How do I prepare my hill village for landslide response?",
    "What should I do if my college hostel has structural cracks?",
    "How do I protect myself if I’m in a basement during a landslide?",
    "What should I do if my school roof collapses?",
    "How do I prepare my family’s health kit for landslide emergencies?",
    "What should I do if my college has no first aid supplies?",
    "How do I help someone with asthma during a landslide?",
    "What should I do if my classroom has broken glass?",
    "How do I prepare my hilltop resort for landslide safety?",
    "What should I do if my school’s water supply is disrupted?",
    "How do I protect myself if I’m in a crowded market?",
    "What should I do if my college hostel is overcrowded?",
    "How do I prepare my family’s emergency contact list?",
    "What should I do if my school’s communication system fails?",
    "How do I help someone who’s lost their belongings?",
    "What should I do if my college has no backup power?",
    "How do I prepare my hill community for landslide drills?"
]
tsunami_queries = [
    "What is a tsunami and how does it form?",
    "What causes tsunamis?",
    "How are tsunamis different from tidal waves?",
    "Can earthquakes trigger tsunamis?",
    "Can volcanic eruptions cause tsunamis?",
    "How fast do tsunami waves travel?",
    "What does a tsunami warning mean?",
    "What are the signs that a tsunami might occur?",
    "Can animals sense tsunamis before they happen?",
    "What is a tsunami watch vs a tsunami warning?",
    "How do underwater landslides cause tsunamis?",
    "What is the Pacific Tsunami Warning Center?",
    "How do scientists predict tsunamis?",
    "What is a megatsunami?",
    "Can tsunamis happen in lakes?",
    "What is the difference between local and distant tsunamis?",
    "How long does a tsunami last?",
    "What does the ocean look like before a tsunami?",
    "Can tsunamis happen without earthquakes?",
    "What are historical examples of deadly tsunamis?",
    "How do I prepare my home for a tsunami?",
    "What should be in a tsunami emergency kit?",
    "How do I create a tsunami evacuation plan?",
    "What should I do if I live near the coast?",
    "How do I protect important documents from water damage?",
    "What foods should I store for tsunami emergencies?",
    "How do I keep my phone charged during a tsunami?",
    "What should I do if my building starts flooding?",
    "How do I know when it’s safe to return home?",
    "What precautions should I take after a tsunami?",
    "How do I disinfect water after a tsunami?",
    "How do I check if my house is structurally safe?",
    "What should I do if my tsunami shelter lacks supplies?",
    "How do I help clean up debris safely?",
    "How do I protect electronics from tsunami damage?",
    "What are the emergency numbers I should save?",
    "How do I prepare my apartment for tsunami safety?",
    "How do I protect my rooftop water tank?",
    "How do I prepare my building’s foundation for tsunamis?",
    "What should I do if my home is damaged by a tsunami?",
    "What should I do if I’m in a classroom during a tsunami?",
    "How do schools prepare for tsunami emergencies?",
    "What should I do if I’m in a college hostel during a tsunami?",
    "How do I prepare my school bag for tsunami emergencies?",
    "What are the safest places in a school building during a tsunami?",
    "How do I help classmates during a tsunami evacuation?",
    "How do I protect classroom electronics?",
    "What should I do if my school bus is caught in a tsunami?",
    "How do I help teachers manage students during a tsunami?",
    "What should I do if my college exams are scheduled during a tsunami?",
    "How do I prepare my hostel room for tsunami safety?",
    "What should I do if my college hostel is damaged?",
    "How do I help classmates with anxiety during a tsunami?",
    "What should I do if my school is used as a shelter?",
    "How do I prepare my college dorm for tsunami safety?",
    "What should I do if my school’s emergency exit is blocked?",
    "How do I help clean up my classroom after a tsunami?",
    "What should I do if my college library is damaged?",
    "How do I prepare my college lab for tsunami safety?",
    "What should I do if my school’s communication system fails?",
    "How do I protect my pets during a tsunami?",
    "What should I do if my pet goes missing during a tsunami?",
    "How do I protect livestock during a tsunami?",
    "What should I do if my pet refuses to evacuate?",
    "What should I do if my pet is scared during a tsunami?",
    "What should I do if my pet needs medical help?",
    "How do I protect my pet’s food and water?",
    "What should I do if my pet is trapped in rubble?",
    "How do I keep pets calm during a tsunami?",
    "How do I prepare a pet emergency kit for tsunamis?",
    "How do I support friends emotionally after a tsunami?",
    "What are the signs of post-tsunami trauma?",
    "How do I prepare mentally for tsunami emergencies?",
    "How do I help someone having a panic attack during a tsunami?",
    "What should I do if I feel unsafe in my current shelter?",
    "How do I help someone who’s unconscious after a tsunami?",
    "How do I help classmates with anxiety during a tsunami?",
    "What should I do if I hear conflicting tsunami information?",
    "How do I stay calm during a tsunami?",
    "How do I support children emotionally after a tsunami?",
    "How do I help elderly neighbors evacuate safely?",
    "How do I help someone with a disability during a tsunami?",
    "What should I do if my family is in another city?",
    "How do I prepare my family for tsunami drills?",
    "How do I prepare my family’s emergency contact list?",
    "How do I protect my family’s health after a tsunami?",
    "How do I help someone with asthma during a tsunami?",
    "What should I do if my family is unreachable?",
    "How do I help someone who’s lost their belongings?",
    "How do I prepare my family’s health kit for tsunami emergencies?",
    "How do I prepare my vehicle for tsunami evacuation?",
    "What should I do if I’m traveling during a tsunami?",
    "How do I stay safe in a coastal resort during a tsunami?",
    "What should I do if I’m in a moving vehicle during a tsunami?",
    "What should I do if I’m in a crowded market during a tsunami?",
    "How do I protect my bicycle or scooter?",
    "What should I do if I’m in a lift during a tsunami?",
    "How do I evacuate safely from a high-rise building?",
    "What should I do if my building’s elevator stops working?",
    "How do I stay informed if the internet goes down during a tsunami?",
    "How do I report tsunami damage?",
    "How do I find tsunami relief centers near me?",
    "What apps send real-time tsunami alerts?",
    "How do I clean up safely after a tsunami?",
    "What should I do if my house is flooded?",
    "How do I protect school supplies from water damage?",
    "What should I do if my college loses power?",
    "What should I do if my school is closed due to tsunami?",
    "What should I do if my college hostel lacks emergency supplies?",
    "What should I do if my college has no backup power?",
    "Which countries are most vulnerable to tsunamis?",
    "Can tsunamis happen in the Indian Ocean?",
    "What are the tsunami risks in coastal India?",
    "How do tsunamis affect island nations?",
    "Can tsunamis reach inland areas?",
    "What are the safest coastal cities during a tsunami?",
    "How do I check tsunami risk for my location?",
    "What are the tsunami zones in my state?",
    "Can tsunamis cross entire oceans?",
    "How do tsunamis affect river mouths and estuaries?",
    "How do tsunami detection buoys work?",
    "What is a tsunami simulation model?",
    "How do satellites help track tsunamis?",
    "What is the role of seismographs in tsunami alerts?",
    "Can AI help predict tsunamis?",
    "How do tsunami sirens work?",
    "What is a tsunami evacuation map?",
    "How do scientists study past tsunamis?",
    "What is a tsunami inundation zone?",
    "How do mobile networks respond to tsunami alerts?",
    "What are common injuries during tsunamis?",
    "How do I treat wounds caused by debris?",
    "What should I do if someone is drowning?",
    "How do I prevent waterborne diseases after a tsunami?",
    "What should be in a tsunami first aid kit?",
    "How do I help someone with diabetes during a tsunami?",
    "What should I do if someone is hypothermic?",
    "How do I find medical help after a tsunami?",
    "What are the risks of contaminated water?",
    "How do I protect myself from mold after flooding?",
    "How do I explain tsunamis to children?",
    "What should I pack in a child’s tsunami kit?",
    "How do I keep children calm during a tsunami?",
    "What should schools teach about tsunami safety?",
    "How do I help a child cope after a tsunami?",
    "What games can teach tsunami preparedness?",
    "How do I help children with disabilities evacuate?",
    "What should I do if my child is at school during a tsunami?",
    "How do I reunite with my child after a tsunami?",
    "How do I support teachers after a tsunami?",
    "How do I navigate flooded roads after a tsunami?",
    "What should I do if GPS stops working?",
    "How do I communicate without internet?",
    "What radio stations give tsunami updates?",
    "How do I send emergency messages?",
    "What should I do if my phone is water-damaged?",
    "How do I find my family after a tsunami?",
    "What are the best offline apps for tsunami alerts?",
    "How do I share my location during a tsunami?",
    "What should I do if I lose all my contacts?"
]
drought_queries = [
    "What is a drought and how does it occur?",
    "What causes droughts in different regions?",
    "How does climate change affect drought frequency?",
    "What are the types of droughts?",
    "What is the difference between meteorological and agricultural drought?",
    "How long can a drought last?",
    "What are the early warning signs of a drought?",
    "Can droughts happen suddenly?",
    "What is a flash drought?",
    "How do scientists monitor drought conditions?",
    "What is the role of groundwater in droughts?",
    "How do droughts affect the water cycle?",
    "What is the Standardized Precipitation Index?",
    "How do droughts impact ecosystems?",
    "Can droughts lead to desertification?",
    "What is the difference between drought and water scarcity?",
    "How do droughts affect rivers and lakes?",
    "What is a hydrological drought?",
    "Can droughts cause wildfires?",
    "What are historical examples of severe droughts?",
    "How do I prepare my home for drought conditions?",
    "What should be in a drought emergency kit?",
    "How do I conserve water during a drought?",
    "What foods should I store for drought emergencies?",
    "How do I keep my garden alive during a drought?",
    "How do I protect important documents from heat damage?",
    "What should I do if my water supply is restricted?",
    "How do I check if my area is drought-prone?",
    "How do I prepare my rooftop tank for drought?",
    "What are the best ways to store water safely?",
    "How do I reduce water usage in my household?",
    "What should I do if my well dries up?",
    "How do I protect electronics from heat damage?",
    "What are the emergency numbers I should save?",
    "How do I prepare my apartment for drought safety?",
    "How do I protect my home from heat stress?",
    "What should I do if my building’s water system fails?",
    "How do I keep pets hydrated during a drought?",
    "How do I prepare my community for drought response?",
    "What are the risks of waterborne diseases during drought?",
    "What should I do if my school has no water?",
    "How do schools prepare for drought emergencies?",
    "How do I help classmates stay hydrated?",
    "What should I do if my college hostel runs out of water?",
    "How do I protect classroom supplies from heat damage?",
    "What should I do if my school’s water tank is empty?",
    "How do I prepare my school bag for drought conditions?",
    "What should I do if my college exams are scheduled during a drought?",
    "How do I help teachers manage students during a drought?",
    "How do I support classmates with health issues during a drought?",
    "What should I do if my school’s water pipes burst?",
    "How do I prepare my hostel room for drought safety?",
    "What should I do if my college library has no cooling?",
    "How do I help clean up my classroom after a heatwave?",
    "What should I do if my school’s emergency exit is blocked?",
    "How do I stay cool in a classroom without fans?",
    "What should I do if my school bus has no water?",
    "How do I protect classroom electronics from overheating?",
    "How do I help classmates with anxiety during a drought?",
    "What should I do if my college hostel lacks emergency supplies?",
    "How do I keep my pets hydrated during a drought?",
    "What should I do if my pet refuses to drink water?",
    "How do I protect livestock during a drought?",
    "What should I do if my pet’s water bowl dries up?",
    "How do I prepare a pet emergency kit for droughts?",
    "What should I do if my pet shows signs of heatstroke?",
    "How do I keep pet food safe in extreme heat?",
    "What should I do if my pet needs medical help during a drought?",
    "How do I find lost animals during a drought?",
    "How do I protect my pet’s shelter from heat?",
    "How do I support friends emotionally during a drought?",
    "What are the signs of heat-related stress?",
    "How do I help someone having a panic attack during a drought?",
    "How do I prepare mentally for drought emergencies?",
    "What should I do if I feel unsafe in my current shelter?",
    "How do I help classmates with anxiety during a drought?",
    "How do I support children emotionally during a drought?",
    "What should I do if I hear conflicting drought information?",
    "How do I stay calm during a drought?",
    "How do I help someone who’s unconscious from heat exhaustion?",
    "How do droughts affect farming?",
    "What crops are drought-resistant?",
    "How do I protect my farmland during a drought?",
    "What irrigation methods work best in droughts?",
    "How do I support farmers during a drought?",
    "What should I do if my village well dries up?",
    "How do I prepare my rural home for drought?",
    "What are government schemes for drought relief?",
    "How do I protect livestock feed during a drought?",
    "What should I do if my crops fail due to drought?",
    "How do I find water sources during a drought?",
    "What apps send real-time drought alerts?",
    "How do I communicate without internet during a drought?",
    "What radio stations give drought updates?",
    "How do I send emergency messages?",
    "What should I do if my phone overheats?",
    "How do I find my family during a drought?",
    "What are the best offline apps for drought alerts?",
    "How do I share my location during a drought?",
    "What should I do if I lose all my contacts?",
    "How do I report drought damage?",
    "How do I find drought relief centers near me?",
    "How do I clean up safely after a drought?",
    "What should I do if my house is damaged by heat?",
    "How do I protect school supplies from heat damage?",
    "What should I do if my college loses power?",
    "What should I do if my school is closed due to drought?",
    "How do I prepare my family for drought drills?",
    "What should I do if my college hostel lacks emergency supplies?",
    "How do I protect my home from drought damage?",
    "How do I find clean drinking water during a drought?",
    "What are low-cost ways to harvest rainwater?",
    "How do I reuse greywater safely?",
    "What are the best water-saving tips for families?",
    "How do I reduce water use in the kitchen?",
    "How do I conserve water while bathing?",
    "What are drought-friendly cleaning habits?",
    "How do I store water for long-term use?",
    "What are signs of dehydration in children?",
    "How do I keep water cool without electricity?",
    "How do I support my village during a drought?",
    "What should I do if my community well dries up?",
    "How do I protect village crops from drought?",
    "What are drought relief schemes for farmers?",
    "How do I help neighbors without water access?",
    "What should I do if my livestock are dehydrated?",
    "How do I organize a water-sharing plan?",
    "What are drought-resistant farming techniques?",
    "How do I protect village children from heatstroke?",
    "How do I prepare my panchayat for drought response?",
    "How do I keep children hydrated at school?",
    "What should I do if my school cancels water supply?",
    "How do I help classmates with heat exhaustion?",
    "What are safe snacks for children during drought?",
    "How do I teach kids about water conservation?",
    "What should I do if my school’s toilets stop working?",
    "How do I support teachers during a drought?",
    "What should I do if my school has no fans?",
    "How do I help classmates with asthma during a drought?",
    "How do I prepare a child’s school kit for drought safety?",
    "How do I stay emotionally strong during a drought?",
    "What are signs of heat-related anxiety?",
    "How do I support someone feeling hopeless during a drought?",
    "How do I talk to children about drought without scaring them?",
    "How do I help someone cope with crop loss?",
    "What are calming techniques during extreme heat?",
    "How do I support elderly family members emotionally?",
    "How do I manage stress when water is scarce?",
    "How do I help someone grieving livestock loss?",
    "How do I stay hopeful during a long drought?",
    "What are symptoms of heatstroke?",
    "How do I treat dehydration at home?",
    "What should I do if someone faints from heat?",
    "How do I prevent skin rashes during drought?",
    "What are safe ways to cool down without AC?",
    "How do I protect my eyes during a dust storm?",
    "What should I do if my medicine needs refrigeration?",
    "How do I keep food safe in extreme heat?",
    "What are first aid tips for heat exhaustion?",
    "How do I protect my health when water is limited?"
]
disaster_queries =[
    "What is a disaster?",
    "How do I prepare for a disaster?",
    "What causes natural disasters?",
    "What should I pack in a disaster kit?",
    "How do I stay calm during a disaster?",
    "What are signs that a disaster is coming?",
    "How do I protect my family from disasters?",
    "What types of disasters affect India?",
    "How do I help children understand disasters?",
    "What is the difference between a hazard and a disaster?",
    "How do I evacuate safely during a disaster?",
    "What should schools do during disasters?",
    "How do I protect pets during disasters?",
    "What documents should I keep ready for disasters?",
    "How do I support elders during a disaster?",
    "What is disaster management?",
    "How do I report a disaster?",
    "What are the phases of disaster response?",
    "How do I find shelter during a disaster?",
    "What is a man-made disaster?",
    "How do I prepare for multiple disasters?",
    "What is the role of community in disaster response?",
    "How do I create a disaster plan?",
    "What is the impact of disasters on mental health?",
    "How do I access medical help during a disaster?",
    "What are the most common disasters in my region?",
    "How do I protect my home from disasters?",
    "What is disaster recovery?",
    "How do I volunteer during a disaster?",
    "What is the role of government in disaster relief?",
    "How do I teach disaster awareness in schools?",
    "What is a slow-onset disaster?",
    "How do I prepare for sudden disasters?",
    "What is a disaster drill?",
    "How do I organize a disaster awareness campaign?",
    "What is disaster risk reduction?",
    "How do I use technology during disasters?",
    "What is a disaster alert system?",
    "How do I prepare a go-bag for disasters?",
    "What is the role of NGOs in disaster response?",
    "How do I protect crops during disasters?",
    "What is a climate-related disaster?",
    "How do I prepare for seasonal disasters?",
    "What is the role of youth in disaster preparedness?",
    "How do I find disaster-safe zones?",
    "What is the impact of disasters on education?",
    "How do I protect livestock during disasters?",
    "What is a cascading disaster?",
    "How do I prepare for compound disasters?",
    "What is the role of media during disasters?",
    "How do I communicate during a disaster?",
    "What is a disaster hotline?",
    "How do I support displaced families after a disaster?",
    "What is disaster insurance?",
    "How do I recover emotionally after a disaster?",
    "What is a disaster response team?",
    "How do I prepare my school for disasters?",
    "What is the role of local leaders in disaster planning?",
    "How do I protect water sources during disasters?",
    "What is a disaster simulation?",
    "How do I prepare for urban disasters?",
    "What is a disaster shelter?",
    "How do I protect digital data during disasters?",
    "What is the role of women in disaster resilience?",
    "How do I prepare for rural disasters?",
    "What is a disaster-resilient building?",
    "How do I protect my business during disasters?",
    "What is a disaster recovery center?",
    "How do I support migrant workers during disasters?",
    "What is the role of schools in disaster education?",
    "How do I prepare for transportation disruptions during disasters?",
    "What is a disaster-safe classroom?",
    "How do I protect cultural heritage during disasters?",
    "What is a disaster-resilient community?",
    "How do I prepare for communication breakdowns during disasters?",
    "What is a disaster impact assessment?",
    "How do I prepare for power outages during disasters?",
    "What is a disaster relief fund?",
    "How do I prepare for food shortages during disasters?",
    "What is a disaster recovery plan?",
    "How do I support people with disabilities during disasters?",
    "What is a disaster early warning system?",
    "How do I prepare for heat-related disasters?",
    "What is a disaster evacuation map?",
    "How do I prepare for water contamination during disasters?",
    "What is a disaster-safe hospital?",
    "How do I prepare for school closures during disasters?",
    "What is a disaster-safe shelter for animals?",
    "How do I prepare for fuel shortages during disasters?",
    "What is a disaster-safe transport route?",
    "How do I prepare for economic loss during disasters?",
    "What is a disaster-safe zone in my city?",
    "How do I prepare for sanitation issues during disasters?",
    "What is a disaster-safe communication plan?",
    "How do I prepare for internet outages during disasters?",
    "What is a disaster-safe evacuation center?",
    "How do I prepare for misinformation during disasters?",
    "What is a disaster-safe food storage method?",
    "How do I prepare for school exams during disasters?",
    "What is a disaster-safe water source?",
    "How do I prepare for mental health support during disasters?",
    "What is a disaster-safe building material?",
    "How do I prepare for community coordination during disasters?",
    "What is a disaster-safe power backup system?",
    "How do I prepare for language barriers during disasters?",
    "What is a disaster-safe sanitation facility?",
    "How do I prepare for medical emergencies during disasters?",
    "What is a disaster-safe education plan?",
    "How do I prepare for pet care during disasters?",
    "What is a disaster-safe storage unit?",
    "How do I prepare for school reopening after disasters?",
    "What is a disaster-safe communication device?",
    "How do I prepare for relocation during disasters?",
    "What is a disaster-safe cooking method?",
    "How do I prepare for community meetings during disasters?",
    "What is a disaster-safe sleeping arrangement?",
    "How do I prepare for school attendance tracking during disasters?",
    "What is a disaster-safe lighting system?",
    "How do I prepare for remote learning during disasters?",
    "What is a disaster-safe transportation hub?",
    "How do I prepare for community outreach during disasters?",
    "What is a disaster-safe emergency contact list?",
    "How do I prepare for school counseling during disasters?",
    "What is a disaster-safe mobile app?",
    "How do I prepare for school nutrition during disasters?",
    "What is a disaster-safe classroom layout?",
    "How do I prepare for school assemblies during disasters?",
    "What is a disaster-safe school timetable?",
    "How do I prepare for school hygiene during disasters?",
    "What is a disaster-safe school evacuation route?",
    "How do I prepare for school communication during disasters?",
    "What is a disaster-safe school supply list?",
    "How do I prepare for school safety drills during disasters?",
    "What is a disaster-safe school transport system?",
    "How do I prepare for school mental health support during disasters?",
    "What is a disaster-safe school attendance system?",
    "How do I prepare for school reopening plans after disasters?",
    "What is a disaster-safe school infrastructure?",
    "How do I prepare for school leadership during disasters?",
    "What is a disaster-safe school community network?",
    "How do I prepare for school-parent coordination during disasters?",
    "What is a disaster-safe school emergency protocol?",
    "How do I prepare for school-based disaster education?",
    "What is a disaster-safe school resource center?",
    "How do I prepare for school-based disaster response teams?",
    "What is a disaster-safe school health check system?",
    "How do I prepare for school-based disaster awareness campaigns?",
    "What is a disaster-safe school digital platform?",
    "How do I prepare for school-based disaster recovery plans?"
  ]










def enrich_student_query(user_input):
    for query in earthquake_queries:
        if query.lower() in user_input.lower():
            return "You are asking about earthquake safety."
    for query in flood_queries:
        if query.lower() in user_input.lower():
            return "You are asking about flood safety."
    for query in fire_queries:
        if query.lower() in user_input.lower():
            return "You are asking about fire safety."
    for query in cyclone_queries:
        if query.lower() in user_input.lower():
            return "You are asking about cyclone safety."
    for query in landslide_queries:
        if query.lower() in user_input.lower():
            return "You are asking about landslide safety."
    for query in tsunami_queries:
        if query.lower() in user_input.lower():
            return "You are asking about tsunmai safety."
    for query in drought_queries:
        if query.lower() in user_input.lower():
            return "You are asking about drought safety."
    for query in disaster_queries:
        if query.lower() in user_input.lower():
            return "You are asking about basic disaster safety."
    
    return "General disaster safety guidance."
