const modules = [
  {
    id: 1,
    category: "Earthquake",
    icon: "🌍",
    title: "Earthquake Safety in India",
    description: "Learn about seismic zones, safe spots, and emergency procedures.",
    progress: 100,
    duration: "45min",
    lessons: 8,
    users: 1247,
    rating: 4.8,
    level: "Beginner",
    button: "Review",
    
  },
  {
    id: 2,
    category: "Flood",
    icon: "💧",
    title: "Monsoon Flood Preparedness",
    description: "Understanding flood risks during monsoons and evacuation strategies.",
    progress: 60,
    duration: "35min",
    lessons: 6,
    users: 987,
    rating: 4.6,
    level: "Beginner",
    button: "Continue",
    
  },
  {
    id: 3,
    category: "Cyclone",
    icon: "🌪",
    title: "Cyclone Emergency Response",
    description: "Coastal areas preparation and storm surge response.",
    progress: 0,
    duration: "40min",
    lessons: 7,
    users: 543,
    rating: 4.7,
    level: "Intermediate",
    button: "Start Learning",
    
  },
   {
    id: 4,
    category: "Fire Safety",
    icon: "🌪",
    title: "School Fire Safety",
    description: "Fire prevention, evacuation routes, and emergency procedures in schools.",
    progress: 0,
    duration: "40min",
    lessons: 7,
    users: 543,
    rating: 4.7,
    level: "Intermediate",
    button: "Start Learning",
    
  },
   {
    id: 5,
    category: "Heat Wave Safety",
    icon: "🌪",
    title: "Heat Wave Safety",
    description: "Recognizing heat-related illnesses and staying safe during extreme temperatures.",
    progress: 0,
    duration: "40min",
    lessons: 7,
    users: 543,
    rating: 4.7,
    level: "Intermediate",
    button: "Start Learning",
    
  },
  {
    id: 6,
    category: "Landslide Risk Awareness",
    icon: "🌪",
    title: "Landslide Risk Awareness",
    description: "Understanding landslide triggers in hilly regions and safety measures.",
    progress: 0,
    duration: "40min",
    lessons: 7,
    users: 543,
    rating: 4.7,
    level: "Intermediate",
    button: "Start Learning",
    
  },
];

export default modules;
